linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - misspell
    - gofmt
    - goimports

linters-settings:
  misspell:
    locale: US
  goimports:
    local-prefixes: github.com/{{ github_username }}

run:
  timeout: 5m

issues:
  exclude-use-default: true
